model_list:
  - model_name: "gpt-5.4"
    litellm_params:
      model: "deepseek/deepseek-v4-flash"
      api_base: "https://openrouter.ai/api/v1"
      api_key: "os.environ/OPENROUTER_API_KEY"
      custom_llm_provider: "openai"
      extra_body:
        reasoning:
          exclude: true

litellm_settings:
  drop_params: true
  num_retries: 3
